### ISSUE TITLE
Bug: spaces in backup dir name

### ISSUE THREAD

**Issue by pbtrung** [X-Ryl669/Frost#8] opened 2015-03-23 15:52 UTC
I still get the error
./Frost --backup /path/to/dir\ name --compression bsc --index index --remote remote --multichunk 10M

error: Bad argument for backup, the --backup parameter is not a folder

**Comment by X-Ryl669** [comment] 2015-03-23 15:55
Duplicate of #6 - Closed for continuing in #6

**Closed by X-Ryl669** 2015-03-23 15:55 UTC
